# Generated by Django 4.2.5 on 2023-09-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0002_alter_bet_end_alter_bet_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="prompt",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
