# Generated by Django 4.2.5 on 2023-09-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0003_bet_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
