# Generated by Django 4.2.5 on 2023-09-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.TextField(unique=True, verbose_name="Username"),
        ),
    ]
